/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};

/* quadrotor_tailsitter_hybrid_reduced_expl_vde_adj:(i0[8],i1[8],i2[3],i3[])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][0] : 0;
  a1=3.6749826614590775e-01;
  a2=1.8108771911090393e+00;
  a3=-2.;
  a4=1.4567793067819208e+00;
  a5=arg[0]? arg[0][3] : 0;
  a6=-2.5419756403955609e+00;
  a5=(a5-a6);
  a5=(a1*a5);
  a6=-1.;
  a5=(a5+a6);
  a7=(a2*a5);
  a8=2.3931486482348954e-01;
  a9=3.1118832547959302e-01;
  a10=arg[0]? arg[0][4] : 0;
  a11=-3.0705725733142577e+00;
  a10=(a10-a11);
  a10=(a9*a10);
  a10=(a10+a6);
  a11=(a8*a10);
  a7=(a7+a11);
  a11=-1.0695162706427333e-01;
  a12=4.0997270933064428e-01;
  a13=arg[0]? arg[0][5] : 0;
  a14=-2.3919465231281181e+00;
  a13=(a13-a14);
  a13=(a12*a13);
  a13=(a13+a6);
  a14=(a11*a13);
  a7=(a7+a14);
  a14=2.1016299812808188e-02;
  a15=1.5572080788488301e+00;
  a16=arg[0]? arg[0][6] : 0;
  a17=-6.4461399335662439e-01;
  a17=(a16-a17);
  a17=(a15*a17);
  a17=(a17+a6);
  a18=(a14*a17);
  a7=(a7+a18);
  a18=-6.4015897544012745e-01;
  a19=1.5909587851027658e+00;
  a20=arg[0]? arg[0][7] : 0;
  a21=-6.1442776930741005e-01;
  a21=(a20-a21);
  a21=(a19*a21);
  a21=(a21+a6);
  a22=(a18*a21);
  a7=(a7+a22);
  a22=4.6054166211247288e-01;
  a23=5.5532058870898062e+00;
  a24=arg[2]? arg[2][0] : 0;
  a25=9.9277110000000016e-02;
  a25=(a24-a25);
  a25=(a23*a25);
  a25=(a25+a6);
  a6=(a22*a25);
  a7=(a7+a6);
  a4=(a4+a7);
  a4=(a3*a4);
  a4=exp(a4);
  a7=2.;
  a6=1.;
  a26=(a6+a4);
  a27=(a7/a26);
  a27=(a27/a26);
  a26=2.4896708815767914e+00;
  a28=4.6244342247185646e+00;
  a29=arg[1]? arg[1][5] : 0;
  a28=(a28*a29);
  a26=(a26*a28);
  a30=-3.4967823531455403e-02;
  a31=4.9103121751769230e+00;
  a32=arg[1]? arg[1][4] : 0;
  a31=(a31*a32);
  a30=(a30*a31);
  a26=(a26+a30);
  a30=-6.1507825155037332e-01;
  a33=6.8041520674609783e+00;
  a34=arg[1]? arg[1][3] : 0;
  a33=(a33*a34);
  a30=(a30*a33);
  a26=(a26+a30);
  a27=(a27*a26);
  a4=(a4*a27);
  a4=(a3*a4);
  a2=(a2*a4);
  a27=-4.4179904282962212e+00;
  a26=-2.7830200400319987e+00;
  a30=(a27*a5);
  a35=4.8639945957677408e+00;
  a36=(a35*a10);
  a30=(a30+a36);
  a36=-4.5105600022864883e-01;
  a37=(a36*a13);
  a30=(a30+a37);
  a37=-3.4414671587691276e-01;
  a38=(a37*a17);
  a30=(a30+a38);
  a38=1.1413028892482451e+00;
  a39=(a38*a21);
  a30=(a30+a39);
  a39=1.4472071836384819e+00;
  a40=(a39*a25);
  a30=(a30+a40);
  a26=(a26+a30);
  a26=(a3*a26);
  a26=exp(a26);
  a30=(a6+a26);
  a40=(a7/a30);
  a40=(a40/a30);
  a30=8.0639052213656082e-02;
  a30=(a30*a28);
  a41=-8.4107795047580813e-02;
  a41=(a41*a31);
  a30=(a30+a41);
  a41=1.2512583654096082e-01;
  a41=(a41*a33);
  a30=(a30+a41);
  a40=(a40*a30);
  a26=(a26*a40);
  a26=(a3*a26);
  a27=(a27*a26);
  a2=(a2+a27);
  a27=-1.2454120365496806e+00;
  a40=-1.3798612635794365e+00;
  a30=(a27*a5);
  a41=-1.8368706160942869e-01;
  a42=(a41*a10);
  a30=(a30+a42);
  a42=5.3470110759699603e-02;
  a43=(a42*a13);
  a30=(a30+a43);
  a43=-1.0564206679013105e-01;
  a44=(a43*a17);
  a30=(a30+a44);
  a44=2.5977065424400442e-01;
  a45=(a44*a21);
  a30=(a30+a45);
  a45=-3.4852036660838215e-01;
  a46=(a45*a25);
  a30=(a30+a46);
  a40=(a40+a30);
  a40=(a3*a40);
  a40=exp(a40);
  a30=(a6+a40);
  a46=(a7/a30);
  a46=(a46/a30);
  a30=4.8563157998693613e+00;
  a30=(a30*a28);
  a47=7.9871092096218302e-02;
  a47=(a47*a31);
  a30=(a30+a47);
  a47=-1.1611986912068993e-01;
  a47=(a47*a33);
  a30=(a30+a47);
  a46=(a46*a30);
  a40=(a40*a46);
  a40=(a3*a40);
  a27=(a27*a40);
  a2=(a2+a27);
  a27=6.9288792431491442e-01;
  a46=-1.1725220422201597e+00;
  a30=(a27*a5);
  a47=2.5645731796286075e-01;
  a48=(a47*a10);
  a30=(a30+a48);
  a48=2.6318846179189861e-02;
  a49=(a48*a13);
  a30=(a30+a49);
  a49=2.1077610254988204e-02;
  a50=(a49*a17);
  a30=(a30+a50);
  a50=7.0051188881161422e-02;
  a51=(a50*a21);
  a30=(a30+a51);
  a51=-2.3643103294950024e-01;
  a52=(a51*a25);
  a30=(a30+a52);
  a46=(a46+a30);
  a46=(a3*a46);
  a46=exp(a46);
  a30=(a6+a46);
  a52=(a7/a30);
  a52=(a52/a30);
  a30=1.8987620162130379e+00;
  a30=(a30*a28);
  a53=-1.8844309860572864e-01;
  a53=(a53*a31);
  a30=(a30+a53);
  a53=-1.3771254778261133e+00;
  a53=(a53*a33);
  a30=(a30+a53);
  a52=(a52*a30);
  a46=(a46*a52);
  a46=(a3*a46);
  a27=(a27*a46);
  a2=(a2+a27);
  a27=-3.7143604184845613e-01;
  a52=7.9266141052629580e-01;
  a5=(a27*a5);
  a30=3.9434086779526173e-01;
  a10=(a30*a10);
  a5=(a5+a10);
  a10=3.0407524097948572e-03;
  a13=(a10*a13);
  a5=(a5+a13);
  a13=-2.4103942536142625e-01;
  a17=(a13*a17);
  a5=(a5+a17);
  a17=2.8926328506273843e-02;
  a21=(a17*a21);
  a5=(a5+a21);
  a21=5.1933371979635913e-02;
  a25=(a21*a25);
  a5=(a5+a25);
  a52=(a52+a5);
  a52=(a3*a52);
  a52=exp(a52);
  a6=(a6+a52);
  a7=(a7/a6);
  a7=(a7/a6);
  a6=-3.7089898465748727e-01;
  a6=(a6*a28);
  a28=-7.5176143678653051e-01;
  a28=(a28*a31);
  a6=(a6+a28);
  a28=5.5822898065557469e-01;
  a28=(a28*a33);
  a6=(a6+a28);
  a7=(a7*a6);
  a52=(a52*a7);
  a3=(a3*a52);
  a27=(a27*a3);
  a2=(a2+a27);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a8=(a8*a4);
  a35=(a35*a26);
  a8=(a8+a35);
  a41=(a41*a40);
  a8=(a8+a41);
  a47=(a47*a46);
  a8=(a8+a47);
  a30=(a30*a3);
  a8=(a8+a30);
  a9=(a9*a8);
  a0=(a0-a9);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a11=(a11*a4);
  a36=(a36*a26);
  a11=(a11+a36);
  a42=(a42*a40);
  a11=(a11+a42);
  a48=(a48*a46);
  a11=(a11+a48);
  a10=(a10*a3);
  a11=(a11+a10);
  a12=(a12*a11);
  a0=(a0-a12);
  if (res[0]!=0) res[0][5]=a0;
  a0=5.9988002399520104e+00;
  a12=arg[1]? arg[1][6] : 0;
  a12=(a0*a12);
  a11=sin(a16);
  a10=cos(a20);
  a48=5.;
  a42=9.8100000000000005e+00;
  a29=(a42*a29);
  a29=(a48*a29);
  a36=(a24*a29);
  a9=(a10*a36);
  a11=(a11*a9);
  a11=(a12+a11);
  a9=cos(a16);
  a32=(a42*a32);
  a32=(a48*a32);
  a8=(a24*a32);
  a9=(a9*a8);
  a11=(a11+a9);
  a14=(a14*a4);
  a37=(a37*a26);
  a14=(a14+a37);
  a43=(a43*a40);
  a14=(a14+a43);
  a49=(a49*a46);
  a14=(a14+a49);
  a13=(a13*a3);
  a14=(a14+a13);
  a15=(a15*a14);
  a11=(a11+a15);
  a15=sin(a16);
  a14=sin(a20);
  a42=(a42*a34);
  a48=(a48*a42);
  a24=(a24*a48);
  a42=(a14*a24);
  a15=(a15*a42);
  a11=(a11+a15);
  a11=(-a11);
  if (res[0]!=0) res[0][6]=a11;
  a11=cos(a20);
  a15=cos(a16);
  a24=(a15*a24);
  a11=(a11*a24);
  a24=arg[1]? arg[1][7] : 0;
  a0=(a0*a24);
  a20=sin(a20);
  a24=cos(a16);
  a36=(a24*a36);
  a20=(a20*a36);
  a20=(a0+a20);
  a18=(a18*a4);
  a38=(a38*a26);
  a18=(a18+a38);
  a44=(a44*a40);
  a18=(a18+a44);
  a50=(a50*a46);
  a18=(a18+a50);
  a17=(a17*a3);
  a18=(a18+a17);
  a19=(a19*a18);
  a20=(a20+a19);
  a11=(a11-a20);
  if (res[0]!=0) res[0][7]=a11;
  a10=(a10*a24);
  a10=(a10*a29);
  a16=sin(a16);
  a16=(a16*a32);
  a10=(a10-a16);
  a22=(a22*a4);
  a39=(a39*a26);
  a22=(a22+a39);
  a45=(a45*a40);
  a22=(a22+a45);
  a51=(a51*a46);
  a22=(a22+a51);
  a21=(a21*a3);
  a22=(a22+a21);
  a23=(a23*a22);
  a10=(a10-a23);
  a14=(a14*a15);
  a14=(a14*a48);
  a10=(a10+a14);
  if (res[0]!=0) res[0][8]=a10;
  if (res[0]!=0) res[0][9]=a12;
  if (res[0]!=0) res[0][10]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_tailsitter_hybrid_reduced_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_tailsitter_hybrid_reduced_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
