/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* quadrotor_tailsitter_hybrid_reduced_expl_ode_fun:(i0[8],i1[3],i2[])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a3=9.8100000000000005e+00;
  a4=arg[0]? arg[0][7] : 0;
  a5=sin(a4);
  a6=arg[0]? arg[0][6] : 0;
  a7=cos(a6);
  a5=(a5*a7);
  a7=arg[1]? arg[1][0] : 0;
  a5=(a5*a7);
  a8=2.0000000000000001e-01;
  a5=(a5/a8);
  a5=(a3*a5);
  a9=-9.3529081535005221e-01;
  a10=5.5822898065557469e-01;
  a11=2.;
  a12=1.;
  a13=-2.;
  a14=7.9266141052629580e-01;
  a15=-3.7143604184845613e-01;
  a16=3.6749826614590775e-01;
  a17=-2.5419756403955609e+00;
  a0=(a0-a17);
  a16=(a16*a0);
  a0=-1.;
  a16=(a16+a0);
  a15=(a15*a16);
  a17=3.9434086779526173e-01;
  a18=3.1118832547959302e-01;
  a19=-3.0705725733142577e+00;
  a1=(a1-a19);
  a18=(a18*a1);
  a18=(a18+a0);
  a17=(a17*a18);
  a15=(a15+a17);
  a17=3.0407524097948572e-03;
  a1=4.0997270933064428e-01;
  a19=-2.3919465231281181e+00;
  a2=(a2-a19);
  a1=(a1*a2);
  a1=(a1+a0);
  a17=(a17*a1);
  a15=(a15+a17);
  a17=-2.4103942536142625e-01;
  a2=1.5572080788488301e+00;
  a19=-6.4461399335662439e-01;
  a19=(a6-a19);
  a2=(a2*a19);
  a2=(a2+a0);
  a17=(a17*a2);
  a15=(a15+a17);
  a17=2.8926328506273843e-02;
  a19=1.5909587851027658e+00;
  a20=-6.1442776930741005e-01;
  a20=(a4-a20);
  a19=(a19*a20);
  a19=(a19+a0);
  a17=(a17*a19);
  a15=(a15+a17);
  a17=5.1933371979635913e-02;
  a20=5.5532058870898062e+00;
  a21=9.9277110000000016e-02;
  a21=(a7-a21);
  a20=(a20*a21);
  a20=(a20+a0);
  a17=(a17*a20);
  a15=(a15+a17);
  a14=(a14+a15);
  a14=(a13*a14);
  a14=exp(a14);
  a14=(a12+a14);
  a14=(a11/a14);
  a14=(a14-a12);
  a10=(a10*a14);
  a15=-1.3771254778261133e+00;
  a17=-1.1725220422201597e+00;
  a21=6.9288792431491442e-01;
  a21=(a21*a16);
  a22=2.5645731796286075e-01;
  a22=(a22*a18);
  a21=(a21+a22);
  a22=2.6318846179189861e-02;
  a22=(a22*a1);
  a21=(a21+a22);
  a22=2.1077610254988204e-02;
  a22=(a22*a2);
  a21=(a21+a22);
  a22=7.0051188881161422e-02;
  a22=(a22*a19);
  a21=(a21+a22);
  a22=-2.3643103294950024e-01;
  a22=(a22*a20);
  a21=(a21+a22);
  a17=(a17+a21);
  a17=(a13*a17);
  a17=exp(a17);
  a17=(a12+a17);
  a17=(a11/a17);
  a17=(a17-a12);
  a15=(a15*a17);
  a10=(a10+a15);
  a15=-1.1611986912068993e-01;
  a21=-1.3798612635794365e+00;
  a22=-1.2454120365496806e+00;
  a22=(a22*a16);
  a23=-1.8368706160942869e-01;
  a23=(a23*a18);
  a22=(a22+a23);
  a23=5.3470110759699603e-02;
  a23=(a23*a1);
  a22=(a22+a23);
  a23=-1.0564206679013105e-01;
  a23=(a23*a2);
  a22=(a22+a23);
  a23=2.5977065424400442e-01;
  a23=(a23*a19);
  a22=(a22+a23);
  a23=-3.4852036660838215e-01;
  a23=(a23*a20);
  a22=(a22+a23);
  a21=(a21+a22);
  a21=(a13*a21);
  a21=exp(a21);
  a21=(a12+a21);
  a21=(a11/a21);
  a21=(a21-a12);
  a15=(a15*a21);
  a10=(a10+a15);
  a15=1.2512583654096082e-01;
  a22=-2.7830200400319987e+00;
  a23=-4.4179904282962212e+00;
  a23=(a23*a16);
  a24=4.8639945957677408e+00;
  a24=(a24*a18);
  a23=(a23+a24);
  a24=-4.5105600022864883e-01;
  a24=(a24*a1);
  a23=(a23+a24);
  a24=-3.4414671587691276e-01;
  a24=(a24*a2);
  a23=(a23+a24);
  a24=1.1413028892482451e+00;
  a24=(a24*a19);
  a23=(a23+a24);
  a24=1.4472071836384819e+00;
  a24=(a24*a20);
  a23=(a23+a24);
  a22=(a22+a23);
  a22=(a13*a22);
  a22=exp(a22);
  a22=(a12+a22);
  a22=(a11/a22);
  a22=(a22-a12);
  a15=(a15*a22);
  a10=(a10+a15);
  a15=-6.1507825155037332e-01;
  a23=1.4567793067819208e+00;
  a24=1.8108771911090393e+00;
  a24=(a24*a16);
  a16=2.3931486482348954e-01;
  a16=(a16*a18);
  a24=(a24+a16);
  a16=-1.0695162706427333e-01;
  a16=(a16*a1);
  a24=(a24+a16);
  a16=2.1016299812808188e-02;
  a16=(a16*a2);
  a24=(a24+a16);
  a16=-6.4015897544012745e-01;
  a16=(a16*a19);
  a24=(a24+a16);
  a16=4.6054166211247288e-01;
  a16=(a16*a20);
  a24=(a24+a16);
  a23=(a23+a24);
  a13=(a13*a23);
  a13=exp(a13);
  a13=(a12+a13);
  a11=(a11/a13);
  a11=(a11-a12);
  a15=(a15*a11);
  a10=(a10+a15);
  a9=(a9+a10);
  a9=(a9-a0);
  a10=1.4696908447743698e-01;
  a9=(a9/a10);
  a10=-6.5141567111656293e+00;
  a9=(a9+a10);
  a5=(a5+a9);
  if (res[0]!=0) res[0][3]=a5;
  a5=7.9246223246909653e-01;
  a9=-7.5176143678653051e-01;
  a9=(a9*a14);
  a10=-1.8844309860572864e-01;
  a10=(a10*a17);
  a9=(a9+a10);
  a10=7.9871092096218302e-02;
  a10=(a10*a21);
  a9=(a9+a10);
  a10=-8.4107795047580813e-02;
  a10=(a10*a22);
  a9=(a9+a10);
  a10=-3.4967823531455403e-02;
  a10=(a10*a11);
  a9=(a9+a10);
  a5=(a5+a9);
  a5=(a5-a0);
  a9=2.0365303962857903e-01;
  a5=(a5/a9);
  a9=-7.1692571293151115e+00;
  a5=(a5+a9);
  a9=sin(a6);
  a9=(a9*a7);
  a9=(a9/a8);
  a9=(a3*a9);
  a5=(a5-a9);
  if (res[0]!=0) res[0][4]=a5;
  a5=-9.8100000000000005e+00;
  a9=cos(a4);
  a10=cos(a6);
  a9=(a9*a10);
  a9=(a9*a7);
  a9=(a9/a8);
  a3=(a3*a9);
  a5=(a5+a3);
  a3=3.7336517701099043e+00;
  a9=-3.7089898465748727e-01;
  a9=(a9*a14);
  a14=1.8987620162130379e+00;
  a14=(a14*a17);
  a9=(a9+a14);
  a14=4.8563157998693613e+00;
  a14=(a14*a21);
  a9=(a9+a14);
  a14=8.0639052213656082e-02;
  a14=(a14*a22);
  a9=(a9+a14);
  a14=2.4896708815767914e+00;
  a14=(a14*a11);
  a9=(a9+a14);
  a3=(a3+a9);
  a3=(a3-a0);
  a0=2.1624266913664630e-01;
  a3=(a3/a0);
  a0=-4.2198053920538641e+00;
  a3=(a3+a0);
  a5=(a5+a3);
  if (res[0]!=0) res[0][5]=a5;
  a5=arg[1]? arg[1][1] : 0;
  a5=(a5-a6);
  a6=1.6669999999999999e-01;
  a5=(a5/a6);
  if (res[0]!=0) res[0][6]=a5;
  a5=arg[1]? arg[1][2] : 0;
  a5=(a5-a4);
  a5=(a5/a6);
  if (res[0]!=0) res[0][7]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_tailsitter_hybrid_reduced_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_tailsitter_hybrid_reduced_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
