# ROS Topics
pose_topic: /mavros/vision_pose/pose
twist_topic: /mavros/local_position/velocity_local

# FSM Parameters
# controller_type: mpc
controller_type: backstepping
# controller_type: slidingmode
enable_logging: false
fsm_frequency: 100
state_timeout: 1.5
rc_timeout: 0.25
odom_timeout: 0.5
command_timeout: 0.25
motor_speedup_time: 5.0
takeoff_height: 1.0
takeoff_land_speed: 0.3
reject_takeoff_twist_threshold: 0.10
hover_max_velocity: 1.5
hover_max_yaw_rate: 1.5
check_safety_volumn: true
safety_volumn: [-2.3, 2.7, -1.7, 2.3, 2.5]

# RC Transmitter Parameters
without_rc: false
throttle_channel: 3
yaw_channel: 4
pitch_channel: 2
roll_channel: 1
fsm_channel: 6
command_channel: 7
reboot_channel: 9
kill_channel: 8
reverse_throttle: true
reverse_yaw: false
reverse_pitch: true
reverse_roll: false
switch_threshold: 0.75
joystick_deadzone: 0.10
check_centered_threshold: 1.0