# q smaller: trust prediction more
# r smaller: trust measurement more

r_pos_x: 2.5e-9
r_pos_y: 2.5e-9
r_pos_z: 2.5e-9
r_vel_x: 2.5e-9
r_vel_y: 2.5e-9
r_vel_z: 2.5e-9
r_control_x: 1.0e-4
r_control_y: 1.0e-4
r_control_z: 1.0e-4

q_pos_x: 1.0e-4
q_pos_y: 1.0e-4
q_pos_z: 1.0e-4
q_vel_x: 1.0e-4
q_vel_y: 1.0e-4
q_vel_z: 1.0e-4
q_disturbance_x: 2.5e-9
q_disturbance_y: 2.5e-9
q_disturbance_z: 2.5e-9
