# q smaller: trust prediction more
# r smaller: trust measurement more

r_pos_x: 4 
r_pos_y: 4
r_pos_z: 4
r_vel_x: 4
r_vel_y: 4
r_vel_z: 4
r_control_x: 2
r_control_y: 2
r_control_z: 2

q_pos_x: 2
q_pos_y: 2
q_pos_z: 2
q_vel_x: 2
q_vel_y: 2
q_vel_z: 2
q_disturbance_x: 4.2
q_disturbance_y: 4.2
q_disturbance_z: 3.5
